spring.application.name=linkedin-backend

# Server Port
server.port=8081

# MySQL Database connection
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/linkedin_clone?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:12345}

# Hibernate ddl auto (update table structure automatically)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Secret (In production, inject this via env variables)
jwt.secret=${JWT_SECRET:9B9483A648D4C82E8A631B725A651711A46761A4E7A2A2D489C4C63C65D65A98}
jwt.expiration=86400000

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:3000}


# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:chikugoyal30375@gmail.com}
spring.mail.password=${MAIL_PASSWORD:zvhbezcbkdnztazq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
 